#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;
#loadURL
url='https://raw.githubusercontent.com/birching01/amh42/master/module';

#info
function amh_module_info()
{
                echo 'AMH-ModuleName: kodexplorer-3.23';
                echo 'AMH-ModuleDescription: KODExplorer是一个公开源码的基于Web的在线文件管理、代码编辑器(默认管理员密码admin：admin)';
                echo 'AMH-ModuleButton: 安装/卸载';
                echo 'AMH-ModuleDate: 2016-10-30';
             	echo 'AMH-ModuleAdmin: ./kodexplorer3.23/index.php';
                echo 'AMH-ModuleWebSite: https://github.com/birching01/amh42';
                echo 'AMH-MoudleScriptBy: birching01';
		echo 'AMH-ModuleIco: ${url}/ico/kodexplorer.png';
}

#install
function amh_module_install()
{
                if amh_module_status ; then
                         exit;
                else
                                cd /home/wwwroot/index/web/;
				mkdir kodexplorer3.23;
				cd kodexplorer3.23;
				wget ${url}/down/kodexplorer3.23.zip;
				unzip kodexplorer3.23.zip;
				chown www:www -R /home/wwwroot/;
				sed "14 a 'kodexplorer' => array('id' => 'kodexplorer', 'url' => './kodexplorer3.23/index.php', 'name' => 'KODExplorer文件管理', 'en' => 'kodexplorer3.23', 'son' => array(	),	), " -i /home/wwwroot/index/web/View/category_list_data.php;
                amh_module_status;				
                fi;
}

#admin
function amh_module_admin()
{
                if amh_module_status ; then
                                echo '[OK] kodexplorer Management:  http://ip:8888/kodexplorer3.23/ ';
                else
                		exit;
                fi;
}

#uninstall
function amh_module_uninstall()
{
                if amh_module_status ; then
                
                sed -i '15d' /home/wwwroot/index/web/View/category_list_data.php;				
                rm -rf /home/wwwroot/index/web/kodexplorer3.23;
				rm -f /root/amh/modules/kodexplorer-3.23.tar.gz;
				chown root:root -R /home/wwwroot/;
				echo '[OK] Uninstall Successful!';
				
                else
				    exit;
		fi;
}

#status
function amh_module_status()
{
                if [ -f "/home/wwwroot/index/web/kodexplorer3.23/index.php" ]; then
                                echo '[OK] KODEXPLORER is already installed.';
                                return 0;
                else
                                echo '[Notice]  KODEXPLORER is not installed.';
                                return 1;
                fi;
}