use `amh`;
TRUNCATE TABLE module_amusers_grant;
TRUNCATE TABLE module_amusers_user_product;
TRUNCATE TABLE module_amusers_controller;
TRUNCATE TABLE module_amusers_item;
TRUNCATE TABLE module_amusers_item_property;
TRUNCATE TABLE module_amusers_item_type;
TRUNCATE TABLE module_amusers_product;


SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- 转存表中的数据 `module_amusers_controller`
--

INSERT INTO `module_amusers_controller` (`controller_id`, `controller_name_cn`, `controller_name_en`, `controller_order`, `controller_time`) VALUES
(18, '账号密码', 'pass', 6, '2013-08-30 00:59:23'),
(15, '虚拟主机', 'host', 0, '2013-08-29 03:01:02'),
(16, 'FTP管理', 'ftp', 2, '2013-08-29 03:03:52');

--
-- 转存表中的数据 `module_amusers_grant`
--

--
-- 转存表中的数据 `module_amusers_item`
--

INSERT INTO `module_amusers_item` (`item_id`, `controller_id`, `item_parent_id`, `item_type_id`, `item_order`, `item_note`) VALUES
(186, 0, 185, 2, 0, ''),
(11, 16, 0, 18, 2, ''),
(201, 0, 200, 18, 0, ''),
(200, 18, 0, 18, 3, ''),
(185, 0, 183, 1, 0, '响应编辑FTP账号'),
(92, 0, 11, 2, 0, 'FTP用户记录列表'),
(119, 0, 11, 18, 3, '新增FTP账号'),
(124, 0, 119, 19, 0, ''),
(125, 0, 119, 1, 0, '响应新增FTP账号'),
(126, 0, 125, 2, 0, ''),
(191, 0, 185, 20, 0, ''),
(149, 0, 125, 20, 0, ''),
(184, 0, 183, 19, 0, ''),
(183, 0, 11, 18, 4, '编辑FTP账号'),
(178, 0, 11, 8, 0, '响应删除FTP'),
(179, 0, 11, 8, 0, '取得编辑FTP数据'),
(202, 0, 204, 2, 0, ''),
(196, 0, 183, 18, 0, ''),
(197, 0, 11, 8, 0, '响应重写目录权限'),
(198, 0, 11, 18, -1, '标题与操作提示'),
(204, 0, 200, 1, 0, '响应更改账号密码'),
(205, 0, 204, 18, 0, ''),
(208, 15, 0, 18, 1, ''),
(209, 0, 208, 18, 0, ''),
(210, 15, 208, 18, 1, ''),
(211, 0, 210, 19, 0, ''),
(212, 0, 210, 1, 0, '响应增加虚拟主机'),
(213, 0, 212, 2, 0, ''),
(214, 0, 212, 18, 0, ''),
(216, 0, 208, 2, 0, '用户虚拟主机列表'),
(217, 0, 208, 8, 0, '响应删除虚拟主机'),
(218, 0, 208, 8, 0, '响应主机停止或启动'),
(219, 0, 208, 8, 0, ' 响应PHP停止或启动'),
(220, 0, 208, 18, 0, ''),
(221, 0, 220, 19, 0, ''),
(222, 0, 220, 1, 0, ' 响应编辑虚拟主机'),
(223, 0, 222, 2, 0, ''),
(224, 0, 222, 18, 0, '');

--
-- 转存表中的数据 `module_amusers_item_property`
--

INSERT INTO `module_amusers_item_property` (`property_id`, `item_id`, `property_type`, `property_name`, `property_value`) VALUES
(29, 92, 'html', 'border', '0'),
(5, 74, 'html', 'text', '主机编号'),
(7, 74, 'html', 'title', '虚拟主机ID'),
(10, 25, 'sql', 'aname', ''),
(14, 103, 'html', 'text', 'ID'),
(15, 104, 'html', 'text', '账号'),
(16, 105, 'html', 'text', '密码'),
(17, 106, 'html', 'text', '根目录'),
(18, 107, 'html', 'text', '目录权限用户'),
(19, 108, 'html', 'text', 'FTP权限用户'),
(20, 94, 'html', 'text', 'ID'),
(21, 95, 'html', 'text', '账号'),
(22, 96, 'html', 'text', '密码'),
(23, 97, 'html', 'text', '根目录'),
(24, 98, 'html', 'text', '目录所属\r\n权限用户'),
(25, 99, 'html', 'text', 'FTP账号\r\n权限用户'),
(26, 100, 'html', 'text', '所属组'),
(27, 101, 'html', 'text', '添加时间'),
(28, 102, 'html', 'text', '操作'),
(30, 92, 'html', 'cellspacing', '1'),
(31, 92, 'html', 'id', 'STable'),
(32, 113, 'html', 'text', 'ok'),
(33, 92, 'html', 'style', 'width:1000px;'),
(34, 114, 'html', 'text', 'ok'),
(40, 122, 'html', 'value', '添加FTP账号'),
(36, 118, 'html', 'text', ' FTP账号管理'),
(37, 120, 'html', 'type', 'text'),
(38, 121, 'html', 'type', 'button'),
(39, 121, 'html', 'value', '提交'),
(41, 122, 'html', 'type', 'button'),
(42, 124, 'html', 'text', '<br />\r\n新增FTP账号:\r\n\r\n'),
(43, 123, 'html', 'text', '&nbsp;'),
(44, 125, 'html', 'method', 'post'),
(46, 129, 'html', 'text', '参数值'),
(47, 130, 'html', 'text', '说明'),
(48, 126, 'html', 'id', 'STable'),
(49, 126, 'html', 'border', '0'),
(50, 126, 'html', 'cellspacing', '1'),
(51, 126, 'html', 'style', 'width:600px;'),
(52, 133, 'html', 'text', '账号'),
(53, 136, 'html', 'type', 'input'),
(54, 136, 'html', 'class', 'input_text '),
(55, 135, 'html', 'text', '<p> &nbsp; <font class="red">*</font> 登录FTP账号</p>'),
(56, 137, 'html', 'text', '密码'),
(57, 140, 'html', 'type', 'password'),
(58, 140, 'html', 'class', 'input_text '),
(59, 142, 'html', 'text', '<td>密码</td>\r\n	<td><input type="password" name="ftp_password" class="input_text" value="" style="width:298px" ></td>\r\n	<td><p> &nbsp; <font class="red">*</font> 登录FTP密码 </p></td>\r\n	'),
(60, 143, 'html', 'text', '<td>权限用户</td>\r\n	<td>\r\n	<select name="ftp_uid_name" id="ftp_uid_name">\r\n	<option value="www">www</option>\r\n	<option value="ftpuser">ftpuser</option>\r\n	</select>\r\n	<script>\r\n	G(''ftp_uid_name'').value = ''ftpuser'';\r\n	</script>\r\n	</td>\r\n	<td><p> &nbsp; <font class="red">*</font> FTP账号所属的权限用户</p></td>\r\n'),
(64, 126, 'html', 'text', '<tr><th></th>\r\n<th>参数值</th>\r\n<th>说明</th>\r\n</tr><tr><td>账号</td>\r\n<td>\r\n<input type="text" name="ftp_name" class="input_text " style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP账号</p></td></tr>\r\n<tr><td>密码</td>\r\n<td>\r\n<input type="password" name="ftp_password" class="input_text" style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP密码 </p></td></tr>\r\n<tr>\r\n<td>主机根目录</td>\r\n<td>\r\n<select name="ftp_root" id="ftp_root">\r\n	<option value="">请选择虚拟主机根目录</option>\r\n	<?php\r\n		foreach ($host_list as $key=>$val)\r\n		{\r\n			echo ''<option value="'' . $val[''host_domain''] . ''">/home/wwwroot/'' . $val[''host_domain''] . ''/web</option>'';\r\n		}\r\n	?>\r\n</select>\r\n\r\n</td>\r\n<td><p> &nbsp; <font class="red">*</font> FTP根目录</p></td></tr>\r\n<tr>\r\n<td>权限用户</td>\r\n<td>\r\n<select name="ftp_uid_name"><option value="www">www</option>\r\n	<option value="ftpuser">ftpuser</option></select></td>\r\n<td><p> &nbsp; <font class="red">*</font> FTP账号所属的权限用户</p></td></tr>'),
(63, 136, 'html', 'style', 'width:298px'),
(65, 144, 'html', 'text', '<button type="submit" class="primary button" name="submit"><span class="check icon"></span>保存</button>'),
(66, 145, 'html', 'text', '<th>ID</th>\r\n<th>账号</th>\r\n<th>密码</th>\r\n<th>根目录</th>\r\n<th>\r\nFTP账号<br />\r\n权限用户</th>\r\n<th>所属组</th>\r\n<th>添加时间</th>\r\n<th>操作</th>'),
(67, 147, 'html', 'text', '<td>账号</td>\r\n<td>\r\n<input type="input" name="ftp_name" class="input_text " style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP账号</p></td>'),
(68, 125, 'amh', 'save_ftp', '{\r\n	"id" : 1,\r\n	"name" : "save_ftp_amh",\r\n	"rules" : {"{$_POST.ftp_name}": "/.{1,20}/", "{$_POST.ftp_password}": "/.+/"},\r\n	"value" : "amh ftp add {$_POST.ftp_name}  {$_POST.ftp_password}  /home/wwwroot/{$_POST.ftp_root}/web 0 0 0 0 0 0 0 0 {$_POST.ftp_uid_name}",\r\n	"notice" : "FTP账号添加失败：请填写完整数据。",\r\n	"success" : "FTP账号添加成功：{$_POST.ftp_name}。",\r\n	"fail" : "FTP账号添加失败：{$_POST.ftp_name}。"\r\n}'),
(70, 125, 'html', 'action', 'index.php?c=amusers_ftp'),
(71, 149, 'html', 'name', 'save_ftp'),
(72, 149, 'html', 'type', 'submit'),
(73, 149, 'html', 'class', 'primary button'),
(74, 149, 'html', 'text', '<span class="check icon"></span>新增'),
(75, 150, 'html', 'style', 'margin:5px 2px;width:500px;'),
(76, 151, 'html', 'id', '<!--AMUsers-Error-ID-->'),
(77, 151, 'html', 'text', '<!--AMUsers-Error-Text-->'),
(78, 153, 'html', 'text', '账号'),
(79, 155, 'html', 'text', '<p> &nbsp; <font class="red">*</font> 登录FTP账号</p>'),
(80, 156, 'html', 'type', 'text'),
(81, 156, 'html', 'name', 'ftp_name'),
(82, 156, 'html', 'class', 'input_text '),
(83, 156, 'html', 'style', 'width:298px'),
(84, 125, 'sql', 'save_ftp', '{\r\n	"id" : 2,\r\n	"name" : "save_ftp_sql",\r\n	"rules" : {"{$_POST.ftp_name}": "/[A-Za-z0-9]{1,20}/"},\r\n	"fetch" : "query",\r\n	"value" : "INSERT INTO amh.amh_ftp(ftp_name, ftp_password, ftp_root, ftp_type, ftp_uid_name) VALUES(''{$_POST.ftp_name}'', ''{$_POST.ftp_password}'', ''/home/wwwroot/{$_POST.ftp_root}/web'', ''web'', ''{$_POST.ftp_uid_name}'')"\r\n}'),
(85, 159, 'html', 'text', '<?php \r\nif(!is_array($ftp_list) || count($ftp_list) < 1)\r\n{\r\n?>\r\n	<tr><td colspan="8" style="padding:10px;">暂无FTP账号</td></tr>\r\n<?php	\r\n}\r\nelse\r\n{\r\n	foreach ($ftp_list as $key=>$val)\r\n	{\r\n?>\r\n		<tr>\r\n		<th class="i"><?php echo $val[''ftp_id''];?></th>\r\n		<td><?php echo $val[''ftp_name''];?></td>\r\n		<td>******</th>\r\n		<td><?php echo $val[''ftp_root''];?></td>\r\n		<td><?php echo $val[''ftp_directory_uname''];?></td>\r\n		<td><?php echo $val[''ftp_uid_name''];?></td>\r\n		<td><?php echo $val[''ftp_type''];?></td>\r\n		<td><?php echo $val[''ftp_time''];?></td>\r\n		<td>\r\n		<?php if($val[''ftp_type''] == ''ssh'') { ?>\r\n		<a href="javascript:" class="button disabled"><span class="pen icon disabled"></span> 编辑</a>\r\n		<a href="javascript:" class="button disabled"><span class="key icon disabled"></span> 重写目录权限</a>\r\n		<a href="javascript:" class="button disabled"><span class="cross icon disabled"></span> 删除</a>\r\n		<?php } else {?>\r\n		<a href="index.php?c=amusers_ftp&edit_ftp=<?php echo urlencode($val[''ftp_name'']);?>" class="button"><span class="pen icon"></span> 编辑</a>\r\n		<a href="index.php?c=amusers_ftp&chown_ftp=<?php echo urlencode($val[''ftp_name'']);?>&uidname=<?php echo $val[''ftp_uid_name''];?>" class="button"  onclick="return confirm(''确认递归重写目录:<?php echo $val[''ftp_root''];?>\\n\\n为FTP账号的<?php echo $val[''ftp_uid_name''];?>用户权限吗?'');"><span class="key icon"></span> 重写目录权限</a>\r\n		<a href="index.php?c=amusers_ftp&del_ftp=<?php echo urlencode($val[''ftp_name'']);?>" class="button" onclick="return confirm(''确认删除FTP账号:<?php echo $val[''ftp_name''];?>?'');"><span class="cross icon"></span> 删除</a>\r\n\r\n		<?php } ?>\r\n		</td>\r\n		</tr>\r\n<?php\r\n	}\r\n}\r\n?>'),
(86, 159, 'data', 'ftp_list', '{\r\n"fatch" : "array",\r\n"value" : "SELECT ftp_id,ftp_name,''***'',ftp_root,ftp_directory_uname,ftp_uid_name,ftp_type,ftp_time FROM amh_ftp"\r\n}'),
(101, 174, 'html', 'text', '密码'),
(102, 176, 'html', 'text', '<p> &nbsp; <font class="red">*</font> 登录FTP密码 </p>'),
(103, 177, 'html', 'type', 'password'),
(88, 162, 'html', 'text', '<td>权限用户</td>\r\n	<td>\r\n	<select name="ftp_uid_name" id="ftp_uid_name">\r\n	<option value="www">www</option>\r\n	<option value="ftpuser">ftpuser</option>\r\n	</select>\r\n	<script>\r\n	G(''ftp_uid_name'').value = ''www'';\r\n	</script>\r\n	</td>\r\n	<td><p> &nbsp; <font class="red">*</font> FTP账号所属的权限用户</p></td>\r\n'),
(89, 164, 'html', 'text', '主机根目录'),
(90, 166, 'html', 'text', '<p> &nbsp; <font class="red">*</font> FTP根目录</p>'),
(91, 168, 'data', 'format', '<option value="$host_id">$host_root</option>'),
(92, 168, 'data', 'query', 'SELECT host_id, host_root FROM `amh_host`'),
(93, 167, 'data', 'format', '<option value="{$host_root}">{$host_root}</option>'),
(94, 167, 'data', 'query', 'SELECT host_id, host_root FROM `amh_host`'),
(96, 167, 'html', 'name', 'ftp_root'),
(97, 170, 'html', 'text', '权限用户'),
(98, 172, 'html', 'text', '<p> &nbsp; <font class="red">*</font> FTP账号所属的权限用户</p>'),
(99, 173, 'html', 'text', '<option value="www">www</option>\r\n	<option value="ftpuser">ftpuser</option>'),
(100, 173, 'html', 'name', 'ftp_uid_name'),
(104, 177, 'html', 'name', 'ftp_password'),
(105, 177, 'html', 'class', 'input_text'),
(106, 177, 'html', 'style', 'width:298px'),
(107, 178, 'html', 'name', 'del_ftp'),
(108, 178, 'html', 'type', 'hidden'),
(109, 178, 'sql', 'del_ftp', '{\r\n"id" : 2,\r\n"value" : "DELETE FROM amh.amh_ftp WHERE ftp_name = ''{$del_ftp_row.data.ftp_name}''",\r\n"note" : "删除数据库FTP账号记录"\r\n}'),
(110, 178, 'amh', 'del_ftp', '{\r\n"id" : 1,\r\n"rules" : {"{$del_ftp_row.data.ftp_name}": "/[A-Za-z0-9]{1,20}/"},\r\n"value" : "amh ftp del {$del_ftp_row.data.ftp_name}",\r\n"notice" : "FTP账号删除失败：错误的FTP用户名。",\r\n"success" : "FTP账号删除成功：{$del_ftp_row.data.ftp_name}",\r\n"fail" : "FTP账号删除失败：{$del_ftp_row.data.ftp_name}",\r\n"note" : "删除FTP账号"\r\n}'),
(111, 179, 'html', 'name', 'edit_ftp'),
(112, 179, 'html', 'type', 'hidden'),
(113, 179, 'sql_data', 'edit_ftp', '{\r\n"name" : "edit_ftp",\r\n"fetch" : "assoc",\r\n"param" : true,\r\n"value" : "SELECT au.user_name, up.*, af.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_ftp AS af ON up.connect_txt = af.ftp_name WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 1 AND af.ftp_name = ''{$_GET.edit_ftp}''",\r\n"note" : "存在edit_ftp参数即取得FTP账号信息"\r\n}'),
(114, 180, 'html', 'text', '<td>账号</td>\r\n<td>\r\n<input type="text" name="ftp_name" class="input_text " style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP账号</p></td>'),
(115, 181, 'html', 'text', '<td>密码</td>\r\n<td>\r\n<input type="password" name="ftp_password" class="input_text" style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP密码 </p></td>'),
(116, 182, 'html', 'text', '\r\n<td>权限用户</td>\r\n<td>\r\n<select name="ftp_uid_name"><option value="www">www</option>\r\n	<option value="ftpuser">ftpuser</option></select></td>\r\n<td><p> &nbsp; <font class="red">*</font> FTP账号所属的权限用户</p></td>'),
(117, 184, 'html', 'text', '<br /> 编辑FTP账号: <?php echo $edit_ftp[''ftp_name''];?>'),
(118, 185, 'html', 'method', 'POST'),
(119, 185, 'html', 'action', 'index.php?c=amusers_ftp'),
(120, 185, 'amh', 'edit_ftp_submit', '{\r\n"id" : 1,\r\n"rules" : {"{$edit_ftp_row.data.ftp_name}": "/.{1,20}/", "{$_POST.ftp_password}": "/.+/"},\r\n"value" : "amh ftp edit {$_POST.ftp_name_edit} - /home/wwwroot/{$_POST.ftp_root_edit}/web 0 0 0 0 0 0 0 0 {$_POST.ftp_uid_name_edit}",\r\n"notice" : "FTP账号编辑失败：请填写完整数据。",\r\n"success" : "FTP账号编辑成功：{$_POST.ftp_name_edit}。",\r\n"fail" : "FTP账号编辑失败：{$_POST.ftp_name_edit}。"\r\n}'),
(121, 185, 'sql', 'edit_ftp_submit', '{\r\n"id" : 2,\r\n"value" : "UPDATE amh.amh_ftp SET ftp_root = ''/home/wwwroot/{$_POST.ftp_root_edit}/web'', ftp_uid_name = ''{$_POST.ftp_uid_name_edit}'' WHERE ftp_name = ''{$_POST.ftp_name_edit}''"\r\n}'),
(122, 185, 'amh', 'edit_ftp_submit', '{\r\n"id" : 3,\r\n"rules" : {"{$_POST.ftp_password_edit}": "/.+/"},\r\n"value" : "amh ftp pass {$_POST.ftp_name_edit} {$_POST.ftp_password_edit}",\r\n"success" : "FTP账号密码更改成功：{$_POST.ftp_name_edit}。",\r\n"fail" : "FTP账号密码更改失败：{$_POST.ftp_name_edit}。",\r\n"note" : "密码不为空时就更改"\r\n}'),
(123, 186, 'html', 'id', 'STable'),
(124, 186, 'html', 'border', '0'),
(125, 186, 'html', 'cellspacing', '1'),
(126, 186, 'html', 'style', 'width:600px;'),
(127, 186, 'html', 'text', '<tr><th></th>\r\n<th>参数值</th>\r\n<th>说明</th>\r\n</tr>\r\n\r\n<tr><td>账号</td>\r\n<td>\r\n<input type="text" name="" class="input_text disabled" value="<?php echo $edit_ftp[''ftp_name''];?>" style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP账号</p>\r\n<input type="hidden" name="ftp_name_edit"  value="<?php echo $edit_ftp[''ftp_name''];?>" />\r\n</td></tr>\r\n\r\n<tr>\r\n<td>密码</td>\r\n<td>\r\n<input type="password" name="ftp_password_edit" class="input_text" style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP密码  [不更改密码请留空] </p></td></tr>\r\n\r\n<tr>\r\n<td>主机根目录</td>\r\n<td>\r\n<select name="ftp_root_edit" id="ftp_root_edit">\r\n	<option value="">请选择虚拟主机根目录</option>\r\n	<?php\r\n		foreach ($host_list as $key=>$val)\r\n		{\r\n			echo ''<option value="'' . $val[''host_domain''] . ''">/home/wwwroot/'' . $val[''host_domain''] . ''/web</option>'';\r\n		}\r\n	?>\r\n</select>\r\n</td>\r\n<td><p> &nbsp; <font class="red">*</font> FTP根目录</p></td></tr>\r\n\r\n<tr>\r\n<td>权限用户</td>\r\n<td>\r\n<select name="ftp_uid_name_edit" id="ftp_uid_name_edit"><option value="www">www</option>\r\n	<option value="ftpuser">ftpuser</option></select></td>\r\n<td><p> &nbsp; <font class="red">*</font> FTP账号所属的权限用户</p></td></tr>'),
(128, 187, 'html', 'text', '<td>账号</td>\r\n<td>\r\n<input type="text" name="" class="input_text disabled" value="<?php echo $edit_ftp[''ftp_name''];?>" style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP账号</p>\r\n<input type="hidden" name="ftp_name_edit"  value="<?php echo $edit_ftp[''ftp_name''];?>" />\r\n</td>'),
(129, 188, 'html', 'text', '<td>密码</td>\r\n<td>\r\n<input type="password" name="ftp_password_edit" class="input_text" style="width:298px"></td>\r\n<td><p> &nbsp; <font class="red">*</font> 登录FTP密码 </p></td>'),
(130, 192, 'html', 'text', '主机根目录'),
(131, 194, 'html', 'text', '<p> &nbsp; <font class="red">*</font> FTP根目录</p>'),
(132, 195, 'data', 'format', '<option value="{$host_root}">{$host_root}</option>'),
(133, 195, 'data', 'query', 'SELECT host_id, host_root FROM `amh_host`'),
(134, 195, 'html', 'name', 'ftp_root_edit'),
(135, 190, 'html', 'text', '<td>权限用户</td>\r\n<td>\r\n<select name="ftp_uid_name_edit" id="ftp_uid_name_edit"><option value="www">www</option>\r\n	<option value="ftpuser">ftpuser</option></select></td>\r\n<td><p> &nbsp; <font class="red">*</font> FTP账号所属的权限用户</p></td>'),
(136, 191, 'html', 'name', 'edit_ftp_submit'),
(137, 191, 'html', 'type', 'submit'),
(138, 191, 'html', 'class', 'primary button'),
(139, 191, 'html', 'text', '<span class="check icon"></span>保存'),
(140, 195, 'html', 'id', 'ftp_root_edit'),
(141, 196, 'html', 'text', '<script>\r\n<?php\r\n$edit_ftp_root = explode(''/'', $edit_ftp[''ftp_root'']);\r\n?>\r\nG(''ftp_root_edit'').value = ''<?php echo $edit_ftp_root[3];?>'';\r\nG(''ftp_uid_name_edit'').value = ''<?php echo $edit_ftp[''ftp_uid_name''];?>'';\r\n</script>'),
(143, 183, 'html', 'style', 'display:<?php if (isset($_GET[''edit_ftp''])) {?> block<?php }else{?>none <?php }?>'),
(144, 119, 'html', 'style', 'display:<?php if (!isset($_GET[''edit_ftp''])) {?> block<?php }else{?>none <?php }?>'),
(145, 197, 'html', 'type', 'hidden'),
(146, 197, 'html', 'name', 'chown_ftp'),
(147, 197, 'amh', 'chown_ftp', '{\r\n"id" : 2,\r\n"rules" : {"{$chown_ftp_row.data.ftp_name}": "/[A-Za-z0-9]{1,20}/"},\r\n"value" : "amh ftp chown {$chown_ftp_row.data.ftp_name} y",\r\n"notice" : "FTP账号重写目录权限失败：错误的FTP用户名",\r\n"success" : "FTP账号重写目录权限成功：{$chown_ftp_row.data.ftp_name}",\r\n"fail" : "FTP账号重写目录权限失败：{$chown_ftp_row.data.ftp_name}"\r\n}'),
(151, 92, 'sql_data', 'ftp_list', '{\n"name" : "ftp_list",\n"fetch" : "array",\n"value" : "SELECT au.user_name, up.*, af.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_ftp AS af ON up.connect_txt = af.ftp_name WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 1 AND af.ftp_name IS NOT NULL",\n"note" : "取得用户FTP账号列表数据"\n}'),
(149, 198, 'html', 'text', '<h2>FTP账号管理</h2>\r\n<?php\r\n	if (!empty($notice)) echo ''<div style="margin:5px 2px;width:500px;"><p id="'' . $status . ''">'' . $notice . ''</p></div>'';\r\n?>'),
(150, 92, 'html', 'text', '<th>ID</th>\r\n<th>账号</th>\r\n<th>密码</th>\r\n<th>根目录</th>\r\n<th>\r\nFTP账号<br />\r\n权限用户</th>\r\n<th>所属组</th>\r\n<th>添加时间</th>\r\n<th>操作</th>\r\n<?php \r\nif(!is_array($ftp_list) || count($ftp_list) < 1)\r\n{\r\n?>\r\n	<tr><td colspan="8" style="padding:10px;">暂无FTP账号</td></tr>\r\n<?php	\r\n}\r\nelse\r\n{\r\n	foreach ($ftp_list as $key=>$val)\r\n	{\r\n?>\r\n		<tr>\r\n		<th class="i"><?php echo $val[''ftp_id''];?></th>\r\n		<td><?php echo $val[''ftp_name''];?></td>\r\n		<td>******</th>\r\n		<td><?php echo $val[''ftp_root''];?></td>\r\n		<td><?php echo $val[''ftp_uid_name''];?></td>\r\n		<td><?php echo $val[''ftp_type''];?></td>\r\n		<td><?php echo $val[''ftp_time''];?></td>\r\n		<td>\r\n		<?php if($val[''ftp_type''] == ''ssh'') { ?>\r\n		<a href="javascript:" class="button disabled"><span class="pen icon disabled"></span> 编辑</a>\r\n		<a href="javascript:" class="button disabled"><span class="key icon disabled"></span> 重写目录权限</a>\r\n		<a href="javascript:" class="button disabled"><span class="cross icon disabled"></span> 删除</a>\r\n		<?php } else {?>\r\n		<a href="index.php?c=amusers_ftp&edit_ftp=<?php echo urlencode($val[''ftp_name'']);?>" class="button"><span class="pen icon"></span> 编辑</a>\r\n		<a href="index.php?c=amusers_ftp&chown_ftp=<?php echo urlencode($val[''ftp_name'']);?>&uidname=<?php echo $val[''ftp_uid_name''];?>" class="button"  onclick="return confirm(''确认递归重写目录:<?php echo $val[''ftp_root''];?>\\n\\n为FTP账号的<?php echo $val[''ftp_uid_name''];?>用户权限吗?'');"><span class="key icon"></span> 重写目录权限</a>\r\n		<a href="index.php?c=amusers_ftp&del_ftp=<?php echo urlencode($val[''ftp_name'']);?>" class="button" onclick="return confirm(''确认删除FTP账号:<?php echo $val[''ftp_name''];?>?'');"><span class="cross icon"></span> 删除</a>\r\n\r\n		<?php } ?>\r\n		<a title="AMFTP-2.0" href="/AMFTP-2.0/index.php?ftp_user=<?php echo urlencode($val[''ftp_name'']);?>" class="button" target="_blank"><span class="cog icon"></span> 管理</a>\r\n		</td>\r\n		</tr>\r\n<?php\r\n	}\r\n}\r\n?>'),
(237, 185, 'sql', 'edit_ftp_submit', '{\r\n"id" : -3,\r\n"name" : "edit_ftp_root_row",\r\n"fetch" : "assoc",\r\n"value" : "SELECT ah.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_host AS ah ON up.connect_txt = ah.host_domain WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 2 AND ah.host_root = ''/home/wwwroot/{$_POST.ftp_root}/web'' ",\r\n"note" : "取得数据，判断是否所属用户的目录。"\r\n}'),
(153, 125, 'sql', 'save_ftp', '{\n	"id" : 3,\n	"value" : "INSERT INTO amh.module_amusers_user_product(user_id, connect_txt , product_id) VALUES (''{$_SESSION.amusers.user_id}'', ''{$_POST.ftp_name}'', ''1'')"\n}'),
(154, 178, 'sql', 'del_ftp', '{\r\n"id" : 0,\r\n"name" : "del_ftp_row",\r\n"value" : "SELECT au.user_name, up.*, af.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_ftp AS af ON up.connect_txt = af.ftp_name WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 1 AND af.ftp_name = ''{$_GET.del_ftp}''",\r\n"fetch" : "assoc",\r\n"note" : "先取得用户FTP账号信息"\r\n}'),
(155, 178, 'sql', 'del_ftp', '{\n"id" : 3,\n"value" : "DELETE FROM module_amusers_user_product WHERE user_product_id = ''{$del_ftp_row.data.user_product_id}'' ",\n"note" : "删除关联记录"\n}'),
(156, 197, 'sql', 'chown_ftp', '{\n"id" : 1,\n"name" : "chown_ftp_row",\n"value" : "SELECT au.user_name, up.*, af.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_ftp AS af ON up.connect_txt = af.ftp_name WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 1 AND af.ftp_name = ''{$_GET.chown_ftp}''",\n"fetch" : "assoc",\n"note" : "先取得用户FTP账号信息"\n}'),
(157, 185, 'sql', 'edit_ftp_submit', '{\n"id" : 0,\n"name" : "edit_ftp_row",\n"value" : "SELECT au.user_name, up.*, af.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_ftp AS af ON up.connect_txt = af.ftp_name WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 1 AND af.ftp_name = ''{$_POST.ftp_name_edit}''",\n"fetch" : "assoc",\n"note" : "先取得用户FTP账号信息"\n}'),
(158, 201, 'html', 'text', '<h2>用户密码更改</h2>\r\n<?php\r\n	if (!empty($notice)) echo ''<div style="margin:5px 2px;width:500px;"><p id="'' . $status . ''">'' . $notice . ''</p></div>'';\r\n?>'),
(159, 202, 'html', 'text', '<tr>\r\n	<th> &nbsp; </th>\r\n	<th>值</th>\r\n<th>说明</th>\r\n	</tr>\r\n	<tr><td>旧密码</td>\r\n	<td><input type="password" name="user_password" class="input_text" value=""></td>\r\n<td><font class="red">*</font> 填写旧密码 长度大于5位</td>\r\n	</tr>\r\n	<tr><td>新密码</td>\r\n	<td><input type="password" name="new_user_password" class="input_text" value=""></td>\r\n<td><font class="red">*</font> 填写新密码 长度大于5位</td>\r\n	</tr>\r\n	<tr><td>确认新密码</td>\r\n	<td><input type="password" name="new_user_password2" class="input_text" value=""></td>\r\n<td><font class="red">*</font> 确认新密码 两次密码需要一致</td>\r\n	</tr>'),
(160, 202, 'html', 'id', 'STable'),
(161, 202, 'html', 'border', '0'),
(162, 202, 'html', 'cellspacing', '1'),
(163, 202, 'html', 'style', 'width:600px;'),
(165, 205, 'html', 'text', '<button type="submit" class="primary button" name="pass_submit"><span class="check icon"></span>更改</button>'),
(166, 204, 'html', 'method', 'post'),
(167, 204, 'html', 'action', 'index.php?c=amusers_pass'),
(168, 204, 'sql', 'pass_submit', '{\r\n"id" : 1,\r\n"rules" : {"{$_POST.new_user_password}" : "/.{6,20}/", "{$_POST.new_user_password2}" : "/.{6,20}/"},\r\n"notice" : "数据请填写正确，新密码需大于5位。"\r\n}'),
(172, 209, 'html', 'text', '<h2>虚拟主机管理</h2>\r\n<?php\r\n	if (!empty($notice)) echo ''<div style="margin:5px 2px;width:500px;"><p id="'' . $status . ''">'' . $notice . ''</p></div>'';\r\n?>'),
(169, 204, 'sql', 'pass_submit', '{\r\n"id" : 2,\r\n"rules" : {"{$_POST.new_user_password}" : "/^{$_POST.new_user_password2}$/"},\r\n"notice" : "新密码两次不一致。"\r\n}'),
(171, 204, 'sql', 'pass_submit', '{\r\n"id" : 3,\r\n"name" : "user_info",\r\n"fetch" : "assoc",\r\n"value" : "SELECT user_name FROM module_amusers_user WHERE user_id = ''{$_SESSION.amusers.user_id}'' AND user_password = md5(md5(''{$_POST.user_password}_amysql-amh'')) "\r\n}'),
(170, 204, 'sql', 'pass_submit', '{\r\n"id" : 4,\r\n"rules" : {"{$user_info.data.user_name}" : "/.+/"},\r\n"value" : "UPDATE module_amusers_user SET user_password = md5(md5(''{$_POST.new_user_password}_amysql-amh'')) WHERE user_id = ''{$_SESSION.amusers.user_id}''",\r\n"notice" : "旧密码错误。",\r\n"success" : "账号密码更改成功。",\r\n"fail" : "账号密码更改失败。"\r\n}'),
(173, 211, 'html', 'text', '<style>\r\n#host_edit input.input_text {\r\nwidth: 300px;\r\n}\r\n</style>\r\n<br /> 新增虚拟主机:'),
(174, 212, 'html', 'method', 'post'),
(175, 212, 'html', 'action', 'index.php?c=amusers_host'),
(176, 213, 'html', 'text', '	<tr>\r\n	<th> &nbsp; </th>\r\n	<th>值</th>\r\n	<th>说明</th>\r\n	</tr>\r\n\r\n	<tr><td>主标识域名</td>\r\n	<td><input type="text" id="host_domain" name="host_domain" class="input_text " value=""></td>\r\n	<td><p> &nbsp; <font class="red">*</font> 用于唯一标识的主域名 </p>\r\n	<p> &nbsp; 不需填写http:// 格式例如: amysql.com</p>\r\n	</td>\r\n	</tr>\r\n\r\n	<tr><td>绑定域名</td>\r\n	<td><input type="text" id="host_server_name" name="host_server_name" class="input_text" value="" <="" td="">\r\n	</td><td><p> &nbsp; 主机绑定的域名，多项请用英文逗号分隔</p>\r\n	<p> &nbsp; 例如: amysql.com,www.amysql.com,bbs.amysql.com  </p>\r\n	</td>\r\n	</tr>\r\n\r\n	<tr><td>默认主页	</td>\r\n	<td><input type="text" name="host_index_name" class="input_text" value="index.html,index.htm,index.php"></td>\r\n	<td><p> &nbsp;  主机默认的主页，多项请用英文逗号分隔 </p></td>\r\n	</tr>\r\n\r\n	<tr><td>Rewrite规则</td>\r\n	<td>\r\n	<select name="host_rewrite" id="host_rewrite">\r\n	<option value="">选择虚拟Rewrite规则</option>\r\n	<?php\r\n		$rl_t = trim($rewrite_list, "\\n");\r\n		$rl_t = explode("\\n", $rl_t);\r\n		foreach ($rl_t as $key=>$val)\r\n			echo ''<option value="'' . $val . ''">'' . $val . ''</option>'';\r\n	?>\r\n	</select>\r\n	<script>\r\n	G(''host_rewrite'').value = ''<?php echo isset($_POST[''host_rewrite'']) ? $_POST[''host_rewrite''] : '''';?>'';\r\n	</script>\r\n	</td>\r\n	<td><p> &nbsp; URL重写规则</p><p> &nbsp; Rewrite存放文件夹 /usr/local/nginx/conf/rewrite</p></td>\r\n	</tr>\r\n	<tr><td>二级域名绑定子目录 </td>\r\n	<td>\r\n	<select name="host_subdirectory" id="host_subdirectory">\r\n	<option value="off">关闭</option>\r\n	<option value="on">开启</option>\r\n	</td>\r\n	<td><p> &nbsp; 是否开启二级域名绑定子目录</p><p> &nbsp; 例如绑定域名:bbs.amysql.com 将自动绑定到网站根目录/bbs</p></td>\r\n	</tr>'),
(177, 213, 'html', 'id', 'STable'),
(178, 213, 'html', 'border', '0'),
(179, 213, 'html', 'cellspacing', '1'),
(180, 213, 'html', 'style', 'width:950px;'),
(181, 213, 'amh_data', 'rewrite_list', '{\r\n"name" : "rewrite_list",\r\n"value" : "amh ls_rewrite"\r\n}'),
(220, 208, 'html', 'id', 'host_edit'),
(183, 214, 'html', 'text', '<button type="submit" class="primary button" name="add_host_submit"><span class="check icon"></span>保存</button>'),
(184, 212, 'amh', 'add_host_submit', '{\r\n	"id" : 1,\r\n	"name" : "add_host_amh",\r\n	"rules" : {"{$_POST.host_domain}": "/^[A-Za-z0-9.-]{1,}$/", "{$_POST.host_server_name}": "/^[A-Za-z0-9.,-]{1,}$/"},\r\n	"value" : " amh host add {$_POST.host_domain} {$_POST.host_server_name} {$_POST.host_index_name} {$_POST.host_rewrite} 0 0 0 {$_POST.host_subdirectory}",\r\n	"notice" : "虚拟主机添加失败：请填写完整数据。",\r\n	"success" : "虚拟主机添加成功：{$_POST.host_domain}。",\r\n	"fail" : "虚拟主机添加失败：{$_POST.host_domain}。"\r\n}'),
(185, 212, 'sql', 'add_host_submit', '{\r\n	"id" : 2,\r\n	"name" : "add_host_sql",\r\n	"fetch" : "query",\r\n	"value" : "INSERT INTO amh.amh_host(host_domain, host_server_name, host_root, host_index_name, host_rewrite, host_subdirectory, host_type) VALUES(''{$_POST.host_domain}'', ''{$_POST.host_server_name}'', ''/home/wwwroot/{$_POST.host_domain}/web'', ''{$_POST.host_index_name}'', ''{$_POST.host_rewrite}'', ''{$_POST.host_subdirectory2}'', ''web'')"\r\n}'),
(186, 212, 'sql', 'add_host_submit', '{\n	"id" : 3,\n	"value" : "INSERT INTO amh.module_amusers_user_product(user_id, connect_txt , product_id) VALUES (''{$_SESSION.amusers.user_id}'', ''{$_POST.host_domain}'', ''2'')"\n}'),
(187, 216, 'html', 'id', 'STable'),
(188, 216, 'html', 'border', '0'),
(189, 216, 'html', 'cellspacing', '1'),
(190, 216, 'html', 'style', 'width:1111px'),
(191, 216, 'html', 'text', '<tr>\r\n	<th>ID</th>\r\n	<th>标识域名</th>\r\n	<th>绑定域名</th>\r\n	<th>网站根目录<br />/home/wwwroot/</th>\r\n	<th>默认主页</th>\r\n	<th>Rewrite<br />规则</th>\r\n	<th>二级域名<br />绑定子目录</th>\r\n	<th>添加时间</th>\r\n	<th>运行维护</th>\r\n	<th>操作</th>\r\n	</tr>\r\n	<?php \r\n	if(!is_array($host_list) && count($host_list) == 0)\r\n	{\r\n	?>\r\n		<tr><td colspan="10" style="padding:10px;">暂无虚拟主机</td></tr>\r\n	<?php	\r\n	}\r\n	else\r\n	{\r\n		foreach ($host_list as $key=>$val)\r\n		{\r\n			$cmd = ''amh cat_php_pid php-fpm-'' . $val[''host_domain''];\r\n			$cmd = Functions::trim_cmd($cmd);\r\n			$val[''host_php''] = strlen(trim(shell_exec($cmd), "\\n")) > 1 ? 1 : 0;\r\n\r\n			$cmd = ''amh cat_vhost '' . $val[''host_domain''];\r\n			$cmd = Functions::trim_cmd($cmd);\r\n			$val[''host_nginx''] = strlen(trim(shell_exec($cmd), "\\n")) > 1 ? 1 : 0;\r\n	?>\r\n			<tr>\r\n			<th class="i"><?php echo $val[''host_id''];?></th>\r\n			<td><?php echo $val[''host_domain''];?></td>\r\n			<td>\r\n			<?php  \r\n				$server_name_arr = explode('','', $val[''host_server_name'']);\r\n				foreach ($server_name_arr as $v)\r\n				{\r\n					if(strpos($v, ''*'') !== false) {\r\n						echo $v . ''<br />'';\r\n					} else {\r\n					?>\r\n					<a href="http://<?php echo $v;?>" target="_blank"><?php echo $v;?></a><br />\r\n			<?php\r\n					}\r\n				}\r\n			?></td>\r\n			<td><?php echo substr($val[''host_root''], 14);?></td>\r\n			<td><?php echo str_replace('','' , ''<br />'', $val[''host_index_name'']);?></td>\r\n			<td><?php echo empty($val[''host_rewrite'']) ? ''无'' : $val[''host_rewrite''];?></td>\r\n			<td><?php echo $val[''host_subdirectory''] == ''1'' ? ''开启'' : ''关闭'';?></td>\r\n			<td><?php echo date(''Y-m-d\\<\\b\\r\\>H:i:s'', strtotime($val[''host_time'']));?>&nbsp; </td>\r\n			<td>\r\n			<a href="index.php?c=amusers_host&host_run=<?php echo $val[''host_domain''];?>&g=<?php echo $val[''host_nginx''] ? ''stop'' : ''start'';?>" >\r\n			<span <?php echo $val[''host_nginx''] ? ''class="run_start" title="主机运行正常"'' : ''class="run_stop" title="主机已停止"'';?>>Host</span>\r\n			</a>\r\n			<a href="index.php?c=amusers_host&php_run=<?php echo $val[''host_domain''];?>&g=<?php echo $val[''host_php''] ? ''stop'' : ''start'';?>">\r\n				<span <?php echo $val[''host_php''] ? ''class="run_start" title="PHP运行正常"'' : ''class="run_stop" title="PHP已停止"'';?>>PHP</span>\r\n			</a>\r\n			<td>\r\n			<a href="index.php?c=amusers_host&edit_host=<?php echo $val[''host_domain''];?>" class="button"><span class="pen icon"></span>编辑</a>\r\n			<a href="index.php?c=amusers_host&del_host=<?php echo $val[''host_domain''];?>" class="button" onclick="return confirm(''确认删除虚拟主机:<?php echo $val[''host_domain''];?>?'');"><span class="cross icon"></span>删除</a>\r\n			</td>\r\n			</tr>\r\n	<?php\r\n		}\r\n	}\r\n	?>'),
(192, 216, 'sql_data', 'host_list', '{\n"name" : "host_list",\n"fetch" : "array",\n"value" : "SELECT au.user_name, up.*, ah.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_host AS ah ON up.connect_txt = ah.host_domain WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 2 AND ah.host_domain IS NOT NULL",\n"note" : "取得用户主机列表数据"\n}'),
(193, 125, 'sql', 'save_ftp', '{\r\n"id" : -5,\r\n"name" : "save_ftp_row",\r\n"fetch" : "assoc",\r\n"value" : "SELECT connect_txt FROM amh.module_amusers_user_product WHERE connect_txt = ''{$_POST.ftp_name}'' AND product_id = ''1''",\r\n"note" : "查询是否存在FTP(多用户数据)"\r\n}'),
(194, 125, 'sql', 'save_ftp', '{\r\n"id" : -4,\r\n"rules" : {"{$save_ftp_row.data.connect_txt}" : "/^$/", "{$save_ftp_row2.data.ftp_name}" : "/^$/"},\r\n"notice" : "FTP账号添加失败：FTP账号已存在。"\r\n}'),
(195, 212, 'sql', 'add_host_submit', '{\r\n"id" : -5,\r\n"name" : "add_host_row",\r\n"fetch" : "assoc",\r\n"value" : "SELECT connect_txt FROM amh.module_amusers_user_product WHERE connect_txt = ''{$_POST.host_domain}'' AND product_id = ''2''",\r\n"note" : "查询是否存在虚拟主机(多用户数据)"\r\n}'),
(196, 212, 'sql', 'add_host_submit', '{\r\n"id" : -4,\r\n"rules" : {"{$add_host_row.data.connect_txt}" : "/^$/", "{$add_host_row2.data.host_domain}" : "/^$/"},\r\n"notice" : "虚拟主机添加失败：虚拟主机已存在。"\r\n}'),
(197, 217, 'html', 'type', 'hidden'),
(198, 217, 'html', 'name', 'del_host'),
(199, 217, 'sql', 'del_host', '{\r\n"id" : 0,\r\n"name" : "del_host_row",\r\n"value" : "SELECT au.user_name, up.*, ah.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_host AS ah ON up.connect_txt = ah.host_domain WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 2 AND ah.host_domain = ''{$_GET.del_host}''",\r\n"fetch" : "assoc",\r\n"note" : "先取得用户虚拟主机记录信息"\r\n}'),
(200, 217, 'amh', 'del_host', '{\r\n"id" : 1,\r\n"rules" : {"{$del_host_row.data.host_domain}": "/.+/"},\r\n"value" : "amh host del {$del_host_row.data.host_domain}",\r\n"notice" : "虚拟主机删除失败：错误的虚拟主机标识域名。",\r\n"success" : "虚拟主机删除成功：{$del_host_row.data.host_domain}",\r\n"fail" : "虚拟主机删除失败：{$del_host_row.data.host_domain}",\r\n"note" : "删除虚拟主机"\r\n}'),
(201, 217, 'sql', 'del_host', '{\r\n"id" : 2,\r\n"value" : "DELETE FROM amh.amh_host WHERE host_domain = ''{$del_host_row.data.host_domain}''",\r\n"note" : "删除数据库虚拟主机记录"\r\n}'),
(202, 217, 'sql', 'del_host', '{\r\n"id" : 3,\r\n"value" : "DELETE FROM module_amusers_user_product WHERE user_product_id = ''{$del_host_row.data.user_product_id}'' ",\r\n"note" : "删除关联记录"\r\n}'),
(203, 218, 'html', 'name', 'host_run'),
(204, 218, 'html', 'type', 'hidden'),
(205, 218, 'sql', 'host_run', '{\r\n"id" : 1,\r\n"rules" : {"{$_GET.g}": "/^(start|stop)$/"},\r\n"name" : "host_run_row",\r\n"fetch" : "assoc",\r\n"value" : "SELECT au.user_name, up.*, ah.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_host AS ah ON up.connect_txt = ah.host_domain WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 2 AND ah.host_domain = ''{$_GET.host_run}''",\r\n"notice" : "虚拟主机{$_GET.g}失败：错误的请求数据。",\r\n"note" : "取得操作的虚拟主机"\r\n}'),
(206, 218, 'amh', 'host_run', '{\r\n"id" : 2,\r\n"rules" : {"{$host_run_row.data.host_domain}": "/.+/"},\r\n"value" : "amh host {$_GET.g} {$host_run_row.data.host_domain}",\r\n"notice" : "虚拟主机{$_GET.g}失败：错误的虚拟主机标识域名。",\r\n"success" : "虚拟主机{$_GET.g}成功：{$host_run_row.data.host_domain}",\r\n"fail" : "虚拟主机{$_GET.g}失败：{$host_run_row.data.host_domain}",\r\n"note" : "虚拟主机启动停止操作"\r\n}'),
(207, 219, 'html', 'name', 'php_run'),
(208, 219, 'html', 'type', 'hidden'),
(209, 219, 'sql', 'php_run', '{\r\n"id" : 1,\r\n"rules" : {"{$_GET.g}": "/^(start|stop)$/"},\r\n"name" : "php_run_row",\r\n"fetch" : "assoc",\r\n"value" : "SELECT au.user_name, up.*, ah.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_host AS ah ON up.connect_txt = ah.host_domain WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 2 AND ah.host_domain = ''{$_GET.php_run}''",\r\n"notice" : "虚拟主机PHP {$_GET.g}失败：错误的请求数据。",\r\n"note" : "取得操作的虚拟主机"\r\n}'),
(210, 219, 'amh', 'php_run', '{\r\n"id" : 2,\r\n"rules" : {"{$php_run_row.data.host_domain}": "/.+/"},\r\n"value" : "amh php {$_GET.g} {$php_run_row.data.host_domain}",\r\n"notice" : "虚拟主机PHP {$_GET.g}失败：错误的虚拟主机标识域名。",\r\n"success" : "虚拟主机PHP {$_GET.g}成功：{$php_run_row.data.host_domain}",\r\n"fail" : "虚拟主机PHP {$_GET.g}失败：{$php_run_row.data.host_domain}"\r\n}'),
(211, 212, 'php', 'add_host_submit', '<?php\r\n\r\n$_POST[''host_domain''] = trim($_POST[''host_domain''], ''.'');\r\n$_POST[''error''] = '''';\r\nif($_POST[''host_domain''] == ''index'' || strpos($_POST[''host_domain''], ''..'') !== false || strpos($_POST[''host_domain''], ''/'') !== false ) \r\n{\r\n	$_POST[''error''] = $_POST[''host_domain''];\r\n}\r\n\r\n\r\n$_POST[''host_subdirectory2''] = $_POST[''host_subdirectory''] == ''on'' ? ''1'' : ''0'';\r\n?>'),
(212, 224, 'html', 'text', '<button type="submit" class="primary button" name="edit_host_submit"><span class="check icon"></span>保存</button>\r\n'),
(213, 223, 'html', 'id', 'STable'),
(214, 223, 'html', 'cellspacing', '1'),
(215, 223, 'html', 'border', '0'),
(216, 223, 'html', 'style', 'width:950px;'),
(217, 221, 'html', 'text', '<br /> 编辑虚拟主机: <?php echo $edit_host_row[''host_domain''];?>'),
(218, 222, 'sql_data', 'edit_host', '{\r\n"name" : "edit_host_row",\r\n"fetch" : "assoc",\r\n"param" : true,\r\n"value" : "SELECT au.user_name, up.*, ah.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_host AS ah ON up.connect_txt = ah.host_domain WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 2 AND ah.host_domain = ''{$_GET.edit_host}''",\r\n"note" : "取得编辑主机数据"\r\n}'),
(219, 223, 'html', 'text', '	<tr>\r\n	<th> &nbsp; </th>\r\n	<th>值</th>\r\n	<th>说明</th>\r\n	</tr>\r\n\r\n	<tr><td>主标识域名</td>\r\n	<td><input type="text" id="host_domain" name="" class="input_text disabled " value="<?php echo $edit_host_row[''host_domain''];?>">\r\n	<input type="hidden" name="host_domain"  value="<?php echo $edit_host_row[''host_domain''];?>" />\r\n	</td>\r\n	<td><p> &nbsp; <font class="red">*</font> 用于唯一标识的主域名 </p>\r\n	<p> &nbsp; 不需填写http:// 格式例如: amysql.com</p>\r\n	</td>\r\n	</tr>\r\n\r\n	<tr><td>绑定域名</td>\r\n	<td><input type="text" id="host_server_name" name="host_server_name" class="input_text" value="<?php echo $edit_host_row[''host_server_name''];?>">\r\n	</td><td><p> &nbsp; 主机绑定的域名，多项请用英文逗号分隔</p>\r\n	<p> &nbsp; 例如: amysql.com,www.amysql.com,bbs.amysql.com  </p>\r\n	</td>\r\n	</tr>\r\n\r\n	<tr><td>默认主页	</td>\r\n	<td><input type="text" name="host_index_name" class="input_text" value="<?php echo $edit_host_row[''host_index_name''];?>"></td>\r\n	<td><p> &nbsp;  主机默认的主页，多项请用英文逗号分隔 </p></td>\r\n	</tr>\r\n\r\n	<tr><td>Rewrite规则</td>\r\n	<td>\r\n	<select name="host_rewrite" id="edit_host_rewrite">\r\n	<option value="">选择虚拟Rewrite规则</option>\r\n	<?php\r\n		$rl_t = trim($rewrite_list, "\\n");\r\n		$rl_t = explode("\\n", $rl_t);\r\n		foreach ($rl_t as $key=>$val)\r\n			echo ''<option value="'' . $val . ''">'' . $val . ''</option>'';\r\n	?>\r\n	</select>\r\n	<script>\r\n	G(''edit_host_rewrite'').value = ''<?php echo isset($edit_host_row[''host_rewrite'']) ? $edit_host_row[''host_rewrite''] : '''';?>'';\r\n	</script>\r\n	</td>\r\n	<td><p> &nbsp; URL重写规则</p><p> &nbsp; Rewrite存放文件夹 /usr/local/nginx/conf/rewrite</p></td>\r\n	</tr>\r\n	<tr><td>二级域名绑定子目录 </td>\r\n	<td>\r\n	<select name="host_subdirectory" id="edit_host_subdirectory">\r\n	<option value="off">关闭</option>\r\n	<option value="on">开启</option>\r\n	<script>\r\n	G(''edit_host_subdirectory'').value = ''<?php echo $edit_host_row[''host_subdirectory''] == ''1'' ? ''on'' : ''off'';?>'';\r\n	</script>\r\n	</td>\r\n	<td><p> &nbsp; 是否开启二级域名绑定子目录</p><p> &nbsp; 例如绑定域名:bbs.amysql.com 将自动绑定到网站根目录/bbs</p></td>\r\n	</tr>'),
(230, 222, 'php', 'edit_host_submit', '<?php\r\n$_POST[''host_subdirectory2''] = $_POST[''host_subdirectory''] == ''on'' ? ''1'' : ''0'';\r\n$_POST[''host_rewrite''] = $_POST[''host_rewrite''] == '''' ? ''amh.conf'' : $_POST[''host_rewrite''];\r\n?>'),
(231, 222, 'amh', 'edit_host_submit', '{\r\n	"id" : 1,\r\n	"name" : "edit_host_amh",\r\n	"rules" : {"{$_POST.host_domain}": "/^[A-Za-z0-9.-]{1,}$/", "{$_POST.host_server_name}": "/^[A-Za-z0-9.,-]{1,}$/"},\r\n	"value" : " amh host edit {$_POST.host_domain} {$_POST.host_server_name} {$_POST.host_index_name} {$_POST.host_rewrite} 0 0 0 {$_POST.host_subdirectory} 0",\r\n	"notice" : "虚拟主机编辑失败：请填写完整数据。",\r\n	"success" : "虚拟主机编辑成功：{$_POST.host_domain}。",\r\n	"fail" : "虚拟主机编辑失败：{$_POST.host_domain}。"\r\n}'),
(224, 210, 'html', 'style', 'display:<?php if (!isset($_GET[''edit_host''])) {?> block<?php }else{?>none <?php }?>'),
(225, 220, 'html', 'style', 'display:<?php if (isset($_GET[''edit_host''])) {?> block<?php }else{?>none <?php }?>'),
(226, 222, 'html', 'method', 'post'),
(227, 222, 'html', 'action', 'index.php?c=amusers_host'),
(228, 222, 'sql', 'edit_host_submit', '{\r\n"id" : -4,\r\n"rules" : {"{$edit_host_row.data.connect_txt}" : "/^.+$/"},\r\n"notice" : "编辑虚拟主机出错：虚拟主机不存在。"\r\n}'),
(229, 222, 'sql', 'edit_host_submit', '{\r\n"id" : -5,\r\n"name" : "edit_host_row",\r\n"fetch" : "assoc",\r\n"value" : "SELECT connect_txt FROM amh.module_amusers_user_product WHERE connect_txt = ''{$_POST.host_domain}'' AND product_id = ''2''",\r\n"note" : "查询是否存在主机"\r\n}'),
(233, 222, 'sql', 'edit_host_submit', '{\r\n	"id" : 2,\r\n	"name" : "edit_host_sql",\r\n	"fetch" : "query",\r\n	"value" : "UPDATE amh.amh_host SET host_server_name = ''{$_POST.host_server_name}'', host_index_name = ''{$_POST.host_index_name}'', host_rewrite = ''{$_POST.host_rewrite}'', host_subdirectory = ''{$_POST.host_subdirectory2}''  WHERE host_domain = ''{$_POST.host_domain}'' "\r\n}'),
(234, 92, 'sql_data', 'host_list', '{\r\n"name" : "host_list",\r\n"fetch" : "array",\r\n"value" : "SELECT ah.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_host AS ah ON up.connect_txt = ah.host_domain WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 2 AND ah.host_domain IS NOT NULL",\r\n"note" : "取得用户主机列表数据"\r\n}'),
(235, 125, 'sql', 'save_ftp', '{\r\n"id" : -3,\r\n"name" : "save_ftp_root_row",\r\n"fetch" : "assoc",\r\n"value" : "SELECT ah.* FROM module_amusers_user AS au LEFT JOIN module_amusers_user_product AS up ON au.user_id = up.user_id LEFT JOIN amh_host AS ah ON up.connect_txt = ah.host_domain WHERE au.user_id = ''{$_SESSION.amusers.user_id}'' AND up.product_id = 2 AND ah.host_root = ''/home/wwwroot/{$_POST.ftp_root}/web'' ",\r\n"note" : "取得数据，判断是否所属用户的目录。"\r\n}'),
(236, 125, 'sql', 'save_ftp', '{\r\n"id" : -2,\r\n"rules" : {"{$save_ftp_root_row.data.host_root}" : "/^.+$/"},\r\n"notice" : "FTP账号添加失败：错误的主机目录。"\r\n}'),
(238, 185, 'sql', 'edit_ftp_submit', '{\r\n"id" : -2,\r\n"rules" : {"{$edit_ftp_root_row.data.host_root}" : "/^.+$/"},\r\n"notice" : "FTP账号添加失败：错误的主机目录。"\r\n}'),
(239, 212, 'sql', 'add_host_submit', '{\r\n"id" : -3,\r\n"rules" : {"{$_POST.error}" : "/^$/"},\r\n"notice" : "虚拟主机添加失败：主标识域名命名错误。"\r\n}'),
(240, 125, 'sql', 'save_ftp', '{\r\n"id" : -5,\r\n"name" : "save_ftp_row2",\r\n"fetch" : "assoc",\r\n"value" : "SELECT * FROM amh.amh_ftp WHERE ftp_name = ''{$_POST.ftp_name}''",\r\n"note" : "查询是否存在FTP"\r\n}'),
(241, 212, 'sql', 'add_host_submit', '{\r\n"id" : -5,\r\n"name" : "add_host_row2",\r\n"fetch" : "assoc",\r\n"value" : "SELECT * FROM amh_host WHERE host_domain = ''{$_POST.host_domain}''",\r\n"note" : "查询是否存在虚拟主机"\r\n}');

--
-- 转存表中的数据 `module_amusers_item_type`
--

INSERT INTO `module_amusers_item_type` (`item_type_id`, `item_type_name`, `item_type_code`, `item_type_order`) VALUES
(1, '表单 FORM', 'form', 1),
(2, '表格 TABLE', 'table', 2),
(3, '表格行 TR', 'tr', 3),
(4, '表格列 TD', 'td', 4),
(7, '文本 FONT', 'font', -7),
(8, ' INPUT 元素', 'input', 8),
(9, '下拉框 SELECT', 'select', 9),
(18, '区域 DIV', 'div', -10),
(13, '多行输入框 TEXTAREA', 'textarea', 13),
(14, '图像 IMG', 'img', 14),
(15, '表格列 TH', 'th', 4),
(19, '换行 P', 'p', -8),
(20, '按钮 BUTTON', 'button', 8),
(17, '标题 H2', 'h2', -9),
(16, '下拉项 OPTION', 'option', 9);

--
-- 转存表中的数据 `module_amusers_product`
--

INSERT INTO `module_amusers_product` (`product_id`, `product_name`) VALUES
(1, 'FTP产品'),
(2, '虚拟主机产品');

--
-- 转存表中的数据 `module_amusers_user_product`
--
