#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;
#loadURL
url='https://raw.githubusercontent.com/birching01/amh42/master/module';

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: phpMyAdmin-4.5.3.1';
		echo 'AMH-ModuleDescription: 最新版本phpMyAdmin-4.5.3.1。面板数据库默认管理系统是由Amysql自主开发的AMS MySQL管理系统，建库建表查看修改删除数据、权限管理等能满足日常操作。部分功能目前还没有phpmyadmin强大，如另需使用phpmyadmin请安装。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2016-04-25';
		echo 'AMH-ModuleAdmin: ./phpmyadmin4531_amh/index.php';
		echo 'AMH-ModuleWebSite: http://www.sxsay.com';
		echo 'AMH-ModuleIco: ${url}/ico/phpmyadmin.gif';
		echo 'AMH-ModuleScriptBy: ぷ咚蟲夏騲ぷ';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
				cd /usr/local/;
				wget ${url}/down/phpMyAdmin-4.5.3.1.tar.gz;
				tar -zxvf phpMyAdmin-4.5.3.1.tar.gz;
				rm -rf phpMyAdmin-4.5.3.1.tar.gz;
				mv phpMyAdmin-4.5.3.1-all-languages /home/wwwroot/index/web/phpmyadmin4531_amh;
				sed -i "/ams=index/a\<input type=\"button\" value=\"phpMyAdmin-4.5.3.1\" onclick=\"WindowOpen('./phpmyadmin4531_amh/index.php');\"/>"  /home/wwwroot/index/web/View/mysql.php;
				amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] phpMyAdmin-4.5.3.1 Management:  http://ip:8888/phpmyadmin4531_amh/ ';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then

				rm -rf /home/wwwroot/index/web/phpmyadmin4531_amh;
				rm -f /usr/local/phpMyAdmin-4.5.3.1.tar.gz;
				sed -i "/phpMyAdmin-4.5.3.1/d" /home/wwwroot/index/web/View/mysql.php;
				echo '[OK] phpMyAdmin-4.5.3.1 Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -d "/home/wwwroot/index/web/phpmyadmin4531_amh" ]; then
				echo '[OK] phpMyAdmin-4.5.3.1 is already installed.';
				return 0;
		else
				echo '[Notice] phpMyAdmin-4.5.3.1 is not installed.';
				return 1;
		fi;
}

