#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
	echo 'AMH-ModuleName: Xcache-3.2.0';
	echo 'AMH-ModuleDescription: XCache 是一个开源的 opcode 缓存器/优化器, 这意味着他能够提高您服务器上的 PHP 性能. 他通过把编译 PHP 后的数据缓冲到共享内存从而避免重复的编译过程, 能够直接使用缓冲区已编译的代码从而提高速度. 通常能够提高您的页面生成速率 2 到5 倍, 降低服务器负载.';
	echo 'AMH-ModuleButton: 安装/卸载';
	echo 'AMH-ModuleDate: 2014-12-20';
	echo 'AMH-ModuleAdmin: ./xcache/index.php';
	echo 'AMH-ModuleWebSite: http://git.oschina.net/renhao/renhao';
	echo 'AMH-ModuleIco: http://xcache.lighttpd.net/chrome/site/xcache.png';
	echo 'AMH-ModuleScriptBy: rose';
}

#install
function amh_module_install()
{
	if amh_module_status ; then
		exit;
	else
		cd /usr/local/;
		wget http://git.oschina.net/renhao/renhao/raw/master/amh-4.2/Module/file/xcache-3.2.0.tar.gz;
		tar -zxvf xcache-3.2.0.tar.gz;
		cd xcache-3.2.0;
		/usr/local/php/bin/phpize;
		./configure --with-php-config=/usr/local/php/bin/php-config --enable-xcache--enable-xcache-coverager --enable-xcache-optimizer;
		make && make install;
		touch /tmp/xcache;
		chmod 777 /tmp/xcache;

cat >> /etc/php.ini <<EOF
[xcache-common]
extension = /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/xcache.so
[xcache.admin]
xcache.admin.enable_auth = On
xcache.admin.user = "amh"
xcache.admin.pass = "9befba9b6ff8b20ef851097bf4d2a8cc"
[xcache]
xcache.shm_scheme ="mmap"
xcache.size=64M
xcache.count =1
xcache.slots =16K
xcache.ttl=0
xcache.gc_interval =0
xcache.var_size=8M
xcache.var_count =2
xcache.var_slots =16K
xcache.var_ttl=0
xcache.var_maxttl=0
xcache.var_gc_interval =300
xcache.test =Off
xcache.readonly_protection = On
xcache.mmap_path ="/tmp/xcache"
xcache.coredump_directory =""
xcache.cacher =On
xcache.stat=On
xcache.optimizer =On
[xcache.coverager]
xcache.coverager =On
xcache.coveragedump_directory =""
EOF
	amh php reload;
	amh_module_status;
	cp -a ./htdocs /home/wwwroot/index/web;
	mv /home/wwwroot/index/web/htdocs /home/wwwroot/index/web/xcache;
	fi;
}

#admin 
function amh_module_admin()
{
	if amh_module_status ; then
		echo '[OK] Xcache-3.2.0  Management: http://ip:8888/xcache/index.php';
	else
		exit;
	fi;
}

#uninstall
function amh_module_uninstall()
{
	if amh_module_status ; then
		cd /usr/local/;
		rm -rf /tmp/xcache;
		rm -rf xcache-3.2.0.tar.gz;
		rm -rf xcache-3.2.0;
		rm -rf /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/xcache.so;
		rm -rf /home/wwwroot/index/web/xcache

		sed -i "/xcache.*/d" /etc/php.ini;
		sed -i "/\[xcache-common\]/d" /etc/php.ini;
		sed -i "/\[xcache.admin\]/d" /etc/php.ini;
		sed -i "/\[xcache.coverager\]/d" /etc/php.ini;
		amh php reload;
		echo '[OK] xcache-3.2.0 Uninstall successful.';
	else
		exit;
	fi;
}

#status
function amh_module_status()
{
	if grep -q '\[xcache\]' /etc/php.ini; then
		echo '[OK] xcache-3.2.0 is already installed.';
		return 0;
	else
		echo '[Notice] xcache-3.2.0 is not installed.';
		return 1;
	fi;
}

